### PR TITLE
Add HAC Ada Compiler

### PR DESCRIPTION
**Pull request by zertovitch**
Added the HAC Ada Compiler.

### CODE REVIEW

**Review by mwasplund — COMMENTED** [review]
Link is correct and verified MIT license and implemented in Ada.

**Comment by mwasplund** [comment]
@zertovitch I am helping out while @dbohdan is out.

How would you characterize the status of this project? Based on the presentation I found on the git repo it looks like it has bee nin active development for the past two years: https://github.com/zertovitch/hac/blob/master/doc/hac_ae_2022_indus.pdf

**Comment by zertovitch** [comment]
The status is "in active development".
Thanks for helping. I hope @dbohdan is fine.

**Comment by dbohdan** [comment]
@zertovitch Thanks for your concern! I am very sick but getting better.

**Comment by dbohdan** [comment]
Okay, this project looks active enough for long enough to add. I'll merge the PR soon.

**Pull request closed without merging**
