### PR TITLE
Added Hades

### PR DESCRIPTION
**Pull request by Azer0s**

### CODE REVIEW

**Comment by dbohdan** [comment]
How mature is Hades? Do you use it in any practical projects? I found it
when researching .NET scripting languages several months ago, but at the
time it looked very early in development with no releases. I didn't put it
on the list then because of this, and I hesitate to do it now. I see that
the project is now at version v0.2-alpha, which still seems very young.

**Comment by Azer0s** [comment]
Thats correct. Hades is still in early development. I´ll get back to you as soon as the language is stable.

**Comment by dbohdan** [comment]
👍

**Comment by TrueFurby** [comment]
I believe there are projects that are useful even in some early versions. New column could be added to represent project's maturity or maybe even put all such experimental projects in separate table.

**Comment by dbohdan** [comment]
Closing as unmaintained. Feel free to resubmit if the project becomes active and matures.

**Pull request closed without merging**
